name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

env:
  REPO_URL: https://github.com/neuro-dev/openwrt.git
  REPO_BRANCH: openwrt-24.10
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  DEPENDENCIES: ${{ github.workspace }}/dependencies-ubuntu.txt
  CUSTOM_FEEDS_SH: ${{ github.workspace }}/custom-feeds.sh
  CUSTOM_PACKAGES_SH: ${{ github.workspace }}/custom-packages.sh
  CUSTOM_CONFIG_SH: ${{ github.workspace }}/custom-config.sh
  PREBUILD_MISC_SH: ${{ github.workspace }}/prebuild-misc.sh
  TZ: Europe/Moscow
  DEVICE_NAME: r2s
  FILE_DATE: unknown
  FIRMWARE: unknown

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -qq update && sudo apt-get -qq upgrade
        sudo apt-get -qq install $(cat $DEPENDENCIES)
        sudo apt-get -qq autoremove --purge
        sudo apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Maximize build disk space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true

    - name: Checkout
      uses: actions/checkout@main

    - name: Download the sources
      run: git clone --branch $REPO_BRANCH $REPO_URL

    - name: Auto select a specific code revision
      id: autoselect
      if: github.event.client_payload.version == 'stable'
      run: |
        cd $BUILD_ROOT && git checkout $(git tag --sort=-creatordate | head -n1)
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Manual select a specific code revision
      id: manualselect
      if: github.event.inputs.version != null && github.event.inputs.version != 'snapshot'
      run: |
        cd $BUILD_ROOT && git checkout ${{ github.event.inputs.version }}
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Load custom
      run: |
        chmod +x *.sh
        $CUSTOM_FEEDS_SH
        $BUILD_ROOT/scripts/feeds update -a && $BUILD_ROOT/scripts/feeds install -a
        $CUSTOM_PACKAGES_SH
        $CUSTOM_CONFIG_SH
        $PREBUILD_MISC_SH

    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      if: github.event.inputs.ssh == 'true'

